### ISSUE TITLE
Difference from e.g. PBKDF2

### ISSUE THREAD

**Issue by msiebuhr** [hyperdivision/derive-key#1]
Why should I use this over other Key Derivation Functions (KDF's), such as [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2)?

Eg. (haven't checked PBKDF2 implementations in JS - purely imagined API...)

```javascript
deriveKey('ns', masterKey, 'name')
// vs
pbkdf2(crypto.HMAC, masterKey, 'ns' + 'name', 1, 32)
```

**Comment by emilbayes** [comment]
@msiebuhr This is only safe if you use a CSPRNG generated seed, so it is not comparable to PBKDF2 or Argon2 (this is not meant for passwords)

**Comment by msiebuhr** [comment]
That sounds like a rather big footgun, IMHO.

Out of curiosity: why not just use PBKDF2 or similar and gain the extra security?

**Comment by emilbayes** [comment]
@msiebuhr this is not for passwords, but for random keys :) PBKDF2 has a different purpose and comes with other properties, eg. entropy stretching at high computational cost (which is a feature!). Here we are already requiring a high entropy string, which is why it can be done with a cryptographic hash function with better predictable security and in a fraction of the time. It's not meant for human input, but a high entropy master key

**Comment by emilbayes** [comment]
I have updated the README accordingly
